name: Trivy

on:
  push: 
    branches:
        - master
        - main

jobs: 
  run: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Python 3.7.9
      - name: Build Image
        run: docker build -t vulnerable-app .
      - name: Install Trivy
        run: |
	    export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')

	    
